package pojos;
// Generated Aug 31, 2019 1:22:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kibocsato generated by hbm2java
 */
@Entity
@Table(name="kibocsato"
    ,catalog="kozlonyv4"
)
public class Kibocsato  implements java.io.Serializable {


     private Integer id;
     private Integer azonosito;
     private String kozlonynev;

    public Kibocsato() {
    }

    public Kibocsato(Integer azonosito, String kozlonynev) {
       this.azonosito = azonosito;
       this.kozlonynev = kozlonynev;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="azonosito")
    public Integer getAzonosito() {
        return this.azonosito;
    }
    
    public void setAzonosito(Integer azonosito) {
        this.azonosito = azonosito;
    }

    
    @Column(name="kozlonynev", length=45)
    public String getKozlonynev() {
        return this.kozlonynev;
    }
    
    public void setKozlonynev(String kozlonynev) {
        this.kozlonynev = kozlonynev;
    }




}


