package pojos;
// Generated Aug 31, 2019 1:22:11 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipus generated by hbm2java
 */
@Entity
@Table(name="tipus"
    ,catalog="kozlonyv4"
)
public class Tipus  implements java.io.Serializable {


     private Integer id;
     private Integer ev;
     private Integer kozlonyszam;
     private String jogszabalyadat;
     private Integer kibocsatoid;

    public Tipus() {
    }

    public Tipus(Integer ev, Integer kozlonyszam, String jogszabalyadat, Integer kibocsatoid) {
       this.ev = ev;
       this.kozlonyszam = kozlonyszam;
       this.jogszabalyadat = jogszabalyadat;
       this.kibocsatoid = kibocsatoid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ev")
    public Integer getEv() {
        return this.ev;
    }
    
    public void setEv(Integer ev) {
        this.ev = ev;
    }

    
    @Column(name="kozlonyszam")
    public Integer getKozlonyszam() {
        return this.kozlonyszam;
    }
    
    public void setKozlonyszam(Integer kozlonyszam) {
        this.kozlonyszam = kozlonyszam;
    }

    
    @Column(name="jogszabalyadat")
    public String getJogszabalyadat() {
        return this.jogszabalyadat;
    }
    
    public void setJogszabalyadat(String jogszabalyadat) {
        this.jogszabalyadat = jogszabalyadat;
    }

    
    @Column(name="kibocsatoid")
    public Integer getKibocsatoid() {
        return this.kibocsatoid;
    }
    
    public void setKibocsatoid(Integer kibocsatoid) {
        this.kibocsatoid = kibocsatoid;
    }




}


